#!/usr/bin/env python3
"""Writes THIRD_PARTY_LICENSES: the license texts of everything compiled into or shipped with
Thurm (the app, thurmd and thurm, and the Linux tarballs). Not committed: macos/build.sh and
the release workflow generate it at build time, so dependency updates never leave it stale.

Crates come from `cargo metadata` (the normal dependencies of thurm-ffi, thurm-daemon and
thurm-cli on the shipped targets) and their own license files. Identical texts are printed
once, with every crate that uses them. Other components are listed in EXTRA.
"""

import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "THIRD_PARTY_LICENSES"
TARGETS = ["aarch64-apple-darwin", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl"]
ROOTS = {"thurm-ffi", "thurm-daemon", "thurm-cli"}
LICENSE_FILE = re.compile(r"^(licen[cs]e|copying|notice|unlicense)([-_.].*)?$", re.IGNORECASE)

# Not crates: (component, where it is used, license files relative to the repo).
EXTRA = [
    ("Ghostty (libghostty-vt)", "terminal emulation, linked into the app, thurmd and thurm",
     ["licenses/ghostty-MIT.txt"]),
    ("Sparkle", "software updates, macOS app", ["licenses/sparkle.txt"]),
    ("iTerm2-Color-Schemes", "built-in color themes", ["crates/thurm-config/themes/LICENSE"]),
    ("tty7 and Fig autocomplete specs", "tab completion specs",
     ["completions/NOTICE", "completions/LICENSE-tty7-Apache-2.0"]),
    ("JetBrains Mono", "bundled font, macOS app", ["macos/Resources/fonts/JetBrainsMono-OFL.txt"]),
    ("Symbols Nerd Font", "bundled font, macOS app", ["macos/Resources/fonts/SymbolsNerdFont-LICENSE"]),
]


def metadata(target):
    out = subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--locked", "--filter-platform", target],
        cwd=ROOT, check=True, capture_output=True, text=True,
    ).stdout
    return json.loads(out)


def shipped_packages():
    """Package id -> package, for every crate linked into the shipped binaries."""
    found = {}
    for target in TARGETS:
        meta = metadata(target)
        packages = {p["id"]: p for p in meta["packages"]}
        nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
        todo = [pid for pid, p in packages.items() if p["name"] in ROOTS and pid in meta["workspace_members"]]
        seen = set()
        while todo:
            pid = todo.pop()
            if pid in seen:
                continue
            seen.add(pid)
            for dep in nodes[pid]["deps"]:
                # Normal dependencies only: build scripts and tests are not shipped.
                if any(k["kind"] is None for k in dep["dep_kinds"]):
                    todo.append(dep["pkg"])
        workspace = set(meta["workspace_members"])
        for pid in seen:
            if pid not in workspace:
                found[pid] = packages[pid]
    return found


def license_texts(pkg):
    root = Path(pkg["manifest_path"]).parent
    files = sorted(p for p in root.iterdir() if p.is_file() and LICENSE_FILE.match(p.name))
    if pkg.get("license_file"):
        extra = root / pkg["license_file"]
        if extra.is_file() and extra not in files:
            files.append(extra)
    return [f.read_text(errors="replace").strip() for f in files]


def render():
    groups = {}  # license text -> [crate labels]
    missing = []
    for pkg in sorted(shipped_packages().values(), key=lambda p: (p["name"], p["version"])):
        label = f"{pkg['name']} {pkg['version']}"
        if pkg.get("license"):
            label += f" ({pkg['license']})"
        texts = license_texts(pkg)
        if not texts:
            missing.append(label)
        for text in texts:
            groups.setdefault(text, []).append(label)

    rule = "=" * 80
    out = [
        "Third-party software in Thurm",
        "",
        "Thurm is licensed under the Apache License 2.0 (see LICENSE). It includes the software",
        "below, under the licenses reproduced here. Generated by scripts/third-party-licenses.py.",
        "",
    ]
    for name, use, files in EXTRA:
        out += [rule, f"{name}: {use}", rule, ""]
        for f in files:
            out += [(ROOT / f).read_text(errors="replace").strip(), ""]
    out += [rule, "Rust crates", rule, ""]
    for text, labels in groups.items():
        out += ["-" * 80, *labels, "-" * 80, "", text, ""]
    if missing:
        out += ["-" * 80, "Crates without a license file (license as declared):", *missing, ""]
    return "\n".join(out).rstrip() + "\n"


def main():
    OUT.write_text(render())
    return 0


if __name__ == "__main__":
    sys.exit(main())
